name: Build and deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'  # Adjust based on your project

    - name: Restore dependencies
      run: dotnet restore
      working-directory: /path/to/your/project  # Ensure this is set correctly

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: /path/to/your/project  # Ensure this is set correctly

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish --no-build
      working-directory: /path/to/your/project  # Ensure this is set correctly

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'your-web-app-name'  # Replace with your Azure Web App name
        slot-name: 'production'  # Default slot is 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
        package: /path/to/your/project/publish  # Ensure this is set correctly
